"""Bimanual coordination primitives for TABLEMIND."""

from __future__ import annotations

from dataclasses import dataclass


Position = tuple[float, float, float]


@dataclass(frozen=True)
class BimanualAssignment:
    """Assign one manipulation object to one robot arm.

    The assignment also carries the target positions generated by
    the reasoning/planning layer so execution does not need to
    invent its own coordinates.
    """

    arm: str
    object_id: str
    approach_position: Position | None = None
    grasp_position: Position | None = None
    lift_position: Position | None = None
    place_position: Position | None = None


@dataclass(frozen=True)
class CoordinatedTask:
    """A coordinated task containing assignments for both arms."""

    name: str
    assignments: tuple[BimanualAssignment, ...]

    def assignment_for(self, arm: str) -> BimanualAssignment:
        """Return the assignment belonging to one arm."""

        for assignment in self.assignments:
            if assignment.arm == arm:
                return assignment

        raise KeyError(
            f"No assignment exists for arm {arm!r}"
        )

    @property
    def arms(self) -> tuple[str, ...]:
        """Return the participating arms."""

        return tuple(
            assignment.arm
            for assignment in self.assignments
        )

    @property
    def objects(self) -> tuple[str, ...]:
        """Return the objects being manipulated."""

        return tuple(
            assignment.object_id
            for assignment in self.assignments
        )


class BimanualCoordinator:
    """Create and validate coordinated two-arm assignments."""

    VALID_ARMS = ("left", "right")

    def create_task(
        self,
        name: str,
        assignments: tuple[BimanualAssignment, ...],
    ) -> CoordinatedTask:
        """Create a validated coordinated task."""

        if not assignments:
            raise ValueError(
                "A coordinated task requires at least one assignment."
            )

        arms = [assignment.arm for assignment in assignments]
        objects = [assignment.object_id for assignment in assignments]

        invalid_arms = set(arms).difference(self.VALID_ARMS)

        if invalid_arms:
            raise ValueError(
                f"Unknown arm(s): {sorted(invalid_arms)}"
            )

        if len(arms) != len(set(arms)):
            raise ValueError(
                "Each arm may appear only once in a coordinated task."
            )

        if len(objects) != len(set(objects)):
            raise ValueError(
                "Each object may appear only once in a coordinated task."
            )

        return CoordinatedTask(
            name=name,
            assignments=assignments,
        )

    def create_two_arm_task(
        self,
        name: str,
        left_object: str,
        right_object: str,
    ) -> CoordinatedTask:
        """Create a standard left/right coordinated task."""

        return self.create_task(
            name=name,
            assignments=(
                BimanualAssignment(
                    arm="left",
                    object_id=left_object,
                ),
                BimanualAssignment(
                    arm="right",
                    object_id=right_object,
                ),
            ),
        )